### ISSUE TITLE
[Unhandled promise rejection: Error: Invalid string. Length must be a multiple of 4]

### ISSUE THREAD

**Issue by Rafaell416** [beatgammit/base64-js#41] opened 2018-04-05 18:51 UTC
```js
import b64 from 'base64-js'
import { ImagePicker } from 'expo'

_pickImageFromGallery = async () => {
    const image = await ImagePicker.launchImageLibraryAsync({ allowsEditing: false, base64: true })
    const byteArray = await b64.toByteArray(image.base64)
}

//result:   [Unhandled promise rejection: Error: Invalid string. Length must be a multiple of 4]
```

**Comment by feross** [comment] 2018-04-12 23:05
Closing this because there's no explanation of your problem here.

**Closed by feross** 2018-04-12 23:05 UTC

**Comment by vith** [comment] 2018-06-12 16:35
The problem is there's no way to treat the padding as optional:

```
> Buffer.from('aGVsbG8gd29ybGQ', 'base64').toString()
'hello world'

> require('base64-js').toByteArray('aGVsbG8gd29ybGQ')
Error: Invalid string. Length must be a multiple of 4
    at getLens (./node_modules/base64-js/index.js:26:11)
    at Object.toByteArray (./node_modules/base64-js/index.js:55:14)

> require('base64-js').toByteArray('aGVsbG8gd29ybGQ=')
Uint8Array [ 104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100 ]
```

Other code that outputs base64 often doesn't include the padding because it's only necessary for decoding if the length of the string is somehow unknown, or if you want to support decoding concatenated strings (which neither base64-js nor Buffer does anyway).

Similarly, it would be convenient if there was an option to not output the padding when going in the other direction.

**Comment by cekvenich** [comment] 2020-07-02 00:30
I'm getting that same error when I encode. I do need padding for my AES down the line. But I assume that this lib would pad, right?
